In [1090]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torchsummary import summary

In [1091]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [1092]:
data = load_iris()

In [1093]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [1094]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [1095]:
data.data.shape

(150, 4)

In [1096]:
data.target.shape

(150,)

In [1097]:
X_train, X_test, Y_train, Y_test = train_test_split(data.data,
                                                    data.target,
                                                    test_size=0.4,
                                                    random_state=7)

In [1098]:
X_valid, X_test, Y_valid, Y_test = train_test_split(X_test,
                                                    Y_test,
                                                    test_size=0.5,
                                                    random_state=7) 

In [1099]:
X_train.shape, X_valid.shape, X_test.shape

((90, 4), (30, 4), (30, 4))

In [1100]:
Y_train.shape, Y_valid.shape, Y_test.shape

((90,), (30,), (30,))

In [1101]:
from sklearn.preprocessing import StandardScaler

In [1102]:
scaler = StandardScaler()

In [1103]:
scaler.fit(X_train)

StandardScaler()

In [1104]:
X_train = scaler.transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

In [1105]:
X_train

array([[-1.03412082,  0.99571559, -1.20196482, -0.77770727],
       [ 1.02069068,  0.08360971,  0.54282282,  0.39755931],
       [ 1.74591826, -0.37244324,  1.44335838,  0.78931484],
       [-0.4297645 , -1.05652265,  0.3739724 ,  0.00580379],
       [-0.79237829, -0.82849618,  0.09255504,  0.26697414],
       [-0.18802197,  3.04795383, -1.25824829, -1.03887762],
       [ 1.625047  ,  0.31163618,  1.27450796,  0.78931484],
       [-0.55063576,  0.76768912, -1.14568135, -1.30004797],
       [-0.0671507 ,  2.13584794, -1.42709871, -1.30004797],
       [ 0.29546309, -1.05652265,  1.04937407,  0.26697414],
       [-0.18802197, -1.28454912,  0.71167324,  1.05048519],
       [-1.27586335, -0.14441676, -1.31453176, -1.43063314],
       [ 0.77894815, -0.14441676,  1.16194102,  1.31165554],
       [-1.51760588,  0.31163618, -1.31453176, -1.30004797],
       [ 0.89981941, -0.37244324,  0.48653935,  0.13638896],
       [ 1.02069068, -0.14441676,  0.82424018,  1.44224071],
       [ 0.29546309, -0.

In [1106]:
X_train = torch.tensor(X_train, dtype=torch.float32)
Y_train = torch.tensor(Y_train, dtype=torch.long)

X_valid = torch.tensor(X_valid, dtype=torch.float32)
Y_valid = torch.tensor(Y_valid, dtype=torch.long)

X_test = torch.tensor(X_test,dtype=torch.float32)
Y_test = torch.tensor(Y_test, dtype=torch.long)

In [1107]:
model = nn.Sequential(
    nn.Linear(4, 8),
    nn.ReLU(),
    nn.Linear(8, 16),
    nn.ReLU(),
    nn.Linear(16, 16),
    nn.ReLU(),
    nn.Linear(16, 8),
    nn.ReLU(),
    nn.Linear(8, 3)
)
model

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=16, bias=True)
  (3): ReLU()
  (4): Linear(in_features=16, out_features=16, bias=True)
  (5): ReLU()
  (6): Linear(in_features=16, out_features=8, bias=True)
  (7): ReLU()
  (8): Linear(in_features=8, out_features=3, bias=True)
)

In [1108]:
summary(model, (90,4))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                [-1, 90, 8]              40
              ReLU-2                [-1, 90, 8]               0
            Linear-3               [-1, 90, 16]             144
              ReLU-4               [-1, 90, 16]               0
            Linear-5               [-1, 90, 16]             272
              ReLU-6               [-1, 90, 16]               0
            Linear-7                [-1, 90, 8]             136
              ReLU-8                [-1, 90, 8]               0
            Linear-9                [-1, 90, 3]              27
Total params: 619
Trainable params: 619
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.07
Params size (MB): 0.00
Estimated Total Size (MB): 0.07
---------------------------------------------------

In [1109]:
X_train[0]

tensor([-1.0341,  0.9957, -1.2020, -0.7777])

In [1110]:
y_pred = model(X_train[0])
y_pred

tensor([ 0.0637, -0.2561,  0.0035], grad_fn=<ViewBackward0>)

In [1111]:
Y_train[0]

tensor(0)

In [1112]:
loss_fn = nn.CrossEntropyLoss()

In [1113]:
learning_rate = 0.01

optimizer = optim.SGD(model.parameters(),
                      learning_rate)

In [1114]:
def evaluate(model, X_valid, Y_valid):
    with torch.no_grad():
        Y_pred = model(X_valid)
    Y_pred = torch.argmax(Y_pred, dim=1)
    return sum(Y_pred == Y_valid) / len(Y_valid)

In [1115]:
evaluate(model, X_valid, Y_valid)

tensor(0.2667)

In [1116]:
num_epoch = 50
losses = []
accs = []

for epoch in range(num_epoch):
    epoch_loss = []
    for x_train, y_train in zip(X_train, Y_train):

        y_pred = model(x_train)

        loss = loss_fn(y_pred, y_train)
        epoch_loss.append(loss.item())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    avg_loss = sum(epoch_loss) / len(epoch_loss)
    losses.append(avg_loss)
    acc_vaild = evaluate(model, X_valid, Y_valid)
    accs.append(acc_vaild.item())
    print(f'Epoch: {epoch}- Loss: {avg_loss} - Acc: {acc_vaild}')

Epoch: 0- Loss: 1.1035462101300557 - Acc: 0.2666666805744171
Epoch: 1- Loss: 1.0981315082973904 - Acc: 0.2666666805744171
Epoch: 2- Loss: 1.0929762529002296 - Acc: 0.2666666805744171
Epoch: 3- Loss: 1.0868095146285164 - Acc: 0.2666666805744171
Epoch: 4- Loss: 1.0767398946815068 - Acc: 0.36666667461395264
Epoch: 5- Loss: 1.0562799831231435 - Acc: 0.6666666865348816
Epoch: 6- Loss: 1.0085437569353315 - Acc: 0.6000000238418579
Epoch: 7- Loss: 0.8959625595145755 - Acc: 0.5666666626930237
Epoch: 8- Loss: 0.7468642609814803 - Acc: 0.5666666626930237
Epoch: 9- Loss: 0.6610524080486762 - Acc: 0.5666666626930237
Epoch: 10- Loss: 0.6131470042384333 - Acc: 0.6000000238418579
Epoch: 11- Loss: 0.5798774342932221 - Acc: 0.7333333492279053
Epoch: 12- Loss: 0.5549129816677628 - Acc: 0.6333333253860474
Epoch: 13- Loss: 0.535227116144314 - Acc: 0.6666666865348816
Epoch: 14- Loss: 0.5197188972818872 - Acc: 0.6666666865348816
Epoch: 15- Loss: 0.5068797683155734 - Acc: 0.6666666865348816
Epoch: 16- Loss: 0

In [1117]:
X_test

tensor([[-0.1880, -1.0565, -0.1326, -0.2554],
        [-0.0672, -0.8285,  0.0926,  0.0058],
        [-1.7593, -0.3724, -1.3145, -1.3000],
        [ 0.6581,  0.0836,  0.9931,  0.7893],
        [ 1.0207, -0.1444,  0.7117,  0.6587],
        [-0.1880, -0.1444,  0.2614,  0.0058],
        [ 0.6581, -0.3724,  0.3177,  0.1364],
        [ 0.0537,  0.3116,  0.5991,  0.7893],
        [ 1.2624,  0.3116,  1.1057,  1.4422],
        [ 0.4163, -0.6005,  0.5991,  0.7893],
        [-0.5506,  1.9078, -1.1457, -1.0389],
        [-1.0341,  0.5397, -1.3145, -1.3000],
        [-0.7924,  2.3639, -1.2582, -1.4306],
        [ 1.6250,  1.2237,  1.3308,  1.7034],
        [-0.4298, -1.5126,  0.0363, -0.1248],
        [-0.9132,  1.6798, -1.2020, -1.3000],
        [-1.5176,  1.2237, -1.5397, -1.3000],
        [-0.5506, -0.1444,  0.4303,  0.3976],
        [ 1.0207, -1.2845,  1.1619,  0.7893],
        [-1.2759, -0.1444, -1.3145, -1.1695],
        [ 0.7789, -0.1444,  0.9931,  0.7893],
        [ 0.2955, -0.3724,  0.5428

In [1118]:
with torch.no_grad():
    Y_pred = model(X_test)

In [1119]:
Y_pred

tensor([[-1.9081,  3.3139, -1.2004],
        [-1.9296,  3.3163, -1.1992],
        [ 6.2798,  0.7324, -3.7381],
        [-5.0460, -0.8511,  2.8761],
        [-4.0860,  0.5480,  1.5208],
        [-1.5804,  3.2734, -1.3805],
        [-1.8779,  3.3169, -1.2564],
        [-3.8924,  0.7767,  1.3158],
        [-6.5765, -2.4021,  4.6828],
        [-4.4466,  0.0866,  1.9570],
        [ 9.4434, -0.1603, -4.8507],
        [ 7.5856,  0.3909, -4.2261],
        [11.7632, -0.9059, -5.6098],
        [-6.8595, -2.7363,  5.0841],
        [-1.9178,  3.3176, -1.1978],
        [10.0591, -0.4064, -5.0253],
        [10.5919, -0.6076, -5.1810],
        [-2.7520,  2.5786, -0.4167],
        [-5.4151, -1.3281,  3.3398],
        [ 5.9042,  0.8993, -3.6527],
        [-5.2220, -1.0663,  3.0757],
        [-2.9856,  2.2807, -0.1325],
        [-1.9175,  3.3188, -1.1980],
        [ 7.3233,  0.4057, -4.0980],
        [-6.8715, -2.6610,  5.0052],
        [ 7.8830,  0.3199, -4.3385],
        [-5.7819, -1.7639,  3.8657],
 

In [1120]:
Y_pred = torch.argmax(Y_pred,dim=1)

In [1121]:
Y_pred

tensor([1, 1, 0, 2, 2, 1, 1, 2, 2, 2, 0, 0, 0, 2, 1, 0, 0, 1, 2, 0, 2, 1, 1, 0,
        2, 0, 2, 0, 0, 1])

In [1122]:
sum(Y_pred == Y_test) / len(Y_test)

tensor(0.9333)